package com.example.albergon.unirank.Model;

import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * This class contains static fields and method useful to store and model countries in the application.
 * It is not instantiable.
 */
public class Countries {

    // private constructor
    private Countries() {}

    public static final Map<String, String> countryMap = createCountryMap();

    public static final Map<String, Integer> iconMap = createCountryIconMap();

    private static Map<String, String> createCountryMap() {

        Map<String, String> codeToName = new HashMap<>();
        codeToName.put("AGO" ,"Angola");
        codeToName.put("ALB" ,"Albania");
        codeToName.put("AND" ,"Andorra");
        codeToName.put("ARE" ,"United Arab Emirates");
        codeToName.put("ARG" ,"Argentina");
        codeToName.put("ARM" ,"Armenia");
        codeToName.put("AUS" ,"Australia");
        codeToName.put("AUT" ,"Austria");
        codeToName.put("AZE" ,"Azerbaijan");
        codeToName.put("BDI" ,"Burundi");
        codeToName.put("BEL" ,"Belgium");
        codeToName.put("BEN" ,"Benin");
        codeToName.put("BFA" ,"Burkina Faso");
        codeToName.put("BGD" ,"Bangladesh");
        codeToName.put("BGR" ,"Bulgaria");
        codeToName.put("BHR" ,"Bahrain");
        codeToName.put("BHS" ,"Bahamas");
        codeToName.put("BIH" ,"Bosnia and Herzegovina");
        codeToName.put("BLR" ,"Belarus");
        codeToName.put("BLZ" ,"Belize");
        codeToName.put("BMU" ,"Bermuda");
        codeToName.put("BOL" ,"Bolivia");
        codeToName.put("BRA" ,"Brazil");
        codeToName.put("BRB" ,"Barbados");
        codeToName.put("BRN" ,"Brunei");
        codeToName.put("BTN" ,"Bhutan");
        codeToName.put("BWA" ,"Botswana");
        codeToName.put("CAF" ,"Central African Republic");
        codeToName.put("CAN" ,"Canada");
        codeToName.put("CHE" ,"Switzerland");
        codeToName.put("CHL" ,"Chile");
        codeToName.put("CHN" ,"China");
        codeToName.put("CIV" ,"Côte d'Ivoire");
        codeToName.put("CMR" ,"Cameroon");
        codeToName.put("COD" ,"Democratic Republic of the Congo");
        codeToName.put("COG" ,"Congo");
        codeToName.put("COL" ,"Colombia");
        codeToName.put("CPV" ,"Cape Verde");
        codeToName.put("CRI" ,"Costa Rica");
        codeToName.put("CUB" ,"Cuba");
        codeToName.put("CYP" ,"Cyprus");
        codeToName.put("CZE" ,"Czech Republic");
        codeToName.put("DEU" ,"Germany");
        codeToName.put("DNK" ,"Denmark");
        codeToName.put("DOM" ,"Dominican Republic");
        codeToName.put("DZA" ,"Algeria");
        codeToName.put("ECU" ,"Ecuador");
        codeToName.put("EGY" ,"Egypt");
        codeToName.put("ERI" ,"Eritrea");
        codeToName.put("ESH" ,"Western Sahara");
        codeToName.put("ESP" ,"Spain");
        codeToName.put("EST" ,"Estonia");
        codeToName.put("ETH" ,"Ethiopia");
        codeToName.put("FIN" ,"Finland");
        codeToName.put("FJI" ,"Fiji");
        codeToName.put("FRA" ,"France");
        codeToName.put("GAB" ,"Gabon");
        codeToName.put("GBR" ,"United Kingdom");
        codeToName.put("GEO" ,"Georgia");
        codeToName.put("GHA" ,"Ghana");
        codeToName.put("GIB" ,"Gibraltar");
        codeToName.put("GIN" ,"Guinea");
        codeToName.put("GLP" ,"Guadeloupe");
        codeToName.put("GMB" ,"Gambia");
        codeToName.put("GNB" ,"Guinea-Bissau");
        codeToName.put("GNQ" ,"Equatorial Guinea");
        codeToName.put("GRC" ,"Greece");
        codeToName.put("GRD" ,"Grenada");
        codeToName.put("GRL" ,"Greenland");
        codeToName.put("GTM" ,"Guatemala");
        codeToName.put("GUF" ,"French Guiana");
        codeToName.put("GUM" ,"Guam");
        codeToName.put("GUY" ,"Guyana");
        codeToName.put("HKG" ,"Hong Kong");
        codeToName.put("HND" ,"Honduras");
        codeToName.put("HRV" ,"Croatia");
        codeToName.put("HTI" ,"Haiti");
        codeToName.put("HUN" ,"Hungary");
        codeToName.put("IDN" ,"Indonesia");
        codeToName.put("IND" ,"India");
        codeToName.put("IRL" ,"Ireland");
        codeToName.put("IRN" ,"Iran");
        codeToName.put("IRQ" ,"Iraq");
        codeToName.put("ISL" ,"Iceland");
        codeToName.put("ISR" ,"Israel");
        codeToName.put("ITA" ,"Italy");
        codeToName.put("JAM" ,"Jamaica");
        codeToName.put("JPN" ,"Japan");
        codeToName.put("KAZ" ,"Kazakhstan");
        codeToName.put("KEN" ,"Kenya");
        codeToName.put("KGZ" ,"Kyrgyzstan");
        codeToName.put("KHM" ,"Cambodia");
        codeToName.put("KOR" ,"South Korea");
        codeToName.put("KWT" ,"Kuwait");
        codeToName.put("LBN" ,"Lebanon");
        codeToName.put("LBR" ,"Liberia");
        codeToName.put("LIE" ,"Liechtenstein");
        codeToName.put("LKA" ,"Sri Lanka");
        codeToName.put("LSO" ,"Lesotho");
        codeToName.put("LTU" ,"Lithuania");
        codeToName.put("LUX" ,"Luxembourg");
        codeToName.put("LVA" ,"Latvia");
        codeToName.put("MAC" ,"Macao");
        codeToName.put("MAR" ,"Morocco");
        codeToName.put("MCO" ,"Monaco");
        codeToName.put("MDA" ,"Moldova");
        codeToName.put("MDG" ,"Madagascar");
        codeToName.put("MDV" ,"Maldives");
        codeToName.put("MEX" ,"Mexico");
        codeToName.put("MKD" ,"Macedonia");
        codeToName.put("MLI" ,"Mali");
        codeToName.put("MLT" ,"Malta");
        codeToName.put("MMR" ,"Myanmar");
        codeToName.put("MNE" ,"Montenegro");
        codeToName.put("MNG" ,"Mongolia");
        codeToName.put("MOZ" ,"Mozambique");
        codeToName.put("MRT" ,"Mauritania");
        codeToName.put("MTQ" ,"Martinique");
        codeToName.put("MUS" ,"Mauritius");
        codeToName.put("MWI" ,"Malawi");
        codeToName.put("MYS" ,"Malaysia");
        codeToName.put("NAM" ,"Namibia");
        codeToName.put("NER" ,"Niger");
        codeToName.put("NGA" ,"Nigeria");
        codeToName.put("NIC" ,"Nicaragua");
        codeToName.put("NLD" ,"Netherlands");
        codeToName.put("NOR" ,"Norway");
        codeToName.put("NPL" ,"Nepal");
        codeToName.put("NZL" ,"New Zealand");
        codeToName.put("OMN" ,"Oman");
        codeToName.put("PAK" ,"Pakistan");
        codeToName.put("PAN" ,"Panama");
        codeToName.put("PER" ,"Peru");
        codeToName.put("PHL" ,"Philippines");
        codeToName.put("PNG" ,"Papua New Guinea");
        codeToName.put("POL" ,"Poland");
        codeToName.put("PRI" ,"Puerto Rico");
        codeToName.put("PRK" ,"North Korea");
        codeToName.put("PRT" ,"Portugal");
        codeToName.put("PRY" ,"Paraguay");
        codeToName.put("QAT" ,"Qatar");
        codeToName.put("ROU" ,"Romania");
        codeToName.put("RUS" ,"Russian Federation");
        codeToName.put("RWA" ,"Rwanda");
        codeToName.put("SAU" ,"Saudi Arabia");
        codeToName.put("SDN" ,"Sudan");
        codeToName.put("SEN" ,"Senegal");
        codeToName.put("SGP" ,"Singapore");
        codeToName.put("SLE" ,"Sierra Leone");
        codeToName.put("SLV" ,"El Salvador");
        codeToName.put("SMR" ,"San Marino");
        codeToName.put("SOM" ,"Somalia");
        codeToName.put("SRB" ,"Serbia");
        codeToName.put("SUR" ,"Suriname");
        codeToName.put("SVK" ,"Slovakia");
        codeToName.put("SVN" ,"Slovenia");
        codeToName.put("SWE" ,"Sweden");
        codeToName.put("SWZ" ,"Swaziland");
        codeToName.put("SYC" ,"Seychelles");
        codeToName.put("SYR" ,"Syrian Arab Republic");
        codeToName.put("TCD" ,"Chad");
        codeToName.put("TGO" ,"Togo");
        codeToName.put("THA" ,"Thailand");
        codeToName.put("TJK" ,"Tajikistan");
        codeToName.put("TKM" ,"Turkmenistan");
        codeToName.put("TON" ,"Tonga");
        codeToName.put("TTO" ,"Trinidad and Tobago");
        codeToName.put("TUN" ,"Tunisia");
        codeToName.put("TUR" ,"Turkey");
        codeToName.put("TWN" ,"Taiwan");
        codeToName.put("TZA" ,"Tanzania");
        codeToName.put("UGA" ,"Uganda");
        codeToName.put("UKR" ,"Ukraine");
        codeToName.put("URY" ,"Uruguay");
        codeToName.put("USA" ,"United States");
        codeToName.put("UZB" ,"Uzbekistan");
        codeToName.put("VEN" ,"Venezuela");
        codeToName.put("VNM" ,"Vietnam");
        codeToName.put("WSM" ,"Samoa");
        codeToName.put("YEM" ,"Yemen");
        codeToName.put("ZAF" ,"South Africa");
        codeToName.put("ZMB" ,"Zambia");
        codeToName.put("ZWE" ,"Zimbabwe");

        return codeToName;
    }

    private static Map<String, Integer> createCountryIconMap() {

        //TODO-ICONS
        Map<String, String> codeToIcon = new HashMap<>();
        //codeToIcon.put("AGO" ,"Angola");
        codeToIcon.put("ALB" ,"Albania");
        codeToIcon.put("AND" ,"Andorra");
        codeToIcon.put("ARE" ,"United Arab Emirates");
        codeToIcon.put("ARG" ,"Argentina");
        codeToIcon.put("ARM" ,"Armenia");
        codeToIcon.put("AUS" ,"Australia");
        codeToIcon.put("AUT" ,"Austria");
        codeToIcon.put("AZE" ,"Azerbaijan");
        codeToIcon.put("BDI" ,"Burundi");
        codeToIcon.put("BEL" ,"Belgium");
        codeToIcon.put("BEN" ,"Benin");
        codeToIcon.put("BFA" ,"Burkina Faso");
        codeToIcon.put("BGD" ,"Bangladesh");
        codeToIcon.put("BGR" ,"Bulgaria");
        codeToIcon.put("BHR" ,"Bahrain");
        codeToIcon.put("BHS" ,"Bahamas");
        codeToIcon.put("BIH" ,"Bosnia and Herzegovina");
        codeToIcon.put("BLR" ,"Belarus");
        codeToIcon.put("BLZ" ,"Belize");
        codeToIcon.put("BMU" ,"Bermuda");
        codeToIcon.put("BOL" ,"Bolivia");
        codeToIcon.put("BRA" ,"Brazil");
        codeToIcon.put("BRB" ,"Barbados");
        codeToIcon.put("BRN" ,"Brunei");
        codeToIcon.put("BTN" ,"Bhutan");
        codeToIcon.put("BWA" ,"Botswana");
        codeToIcon.put("CAF" ,"Central African Republic");
        codeToIcon.put("CAN" ,"Canada");
        codeToIcon.put("CHE" ,"Switzerland");
        codeToIcon.put("CHL" ,"Chile");
        codeToIcon.put("CHN" ,"China");
        codeToIcon.put("CIV" ,"Côte d'Ivoire");
        codeToIcon.put("CMR" ,"Cameroon");
        codeToIcon.put("COD" ,"Democratic Republic of the Congo");
        codeToIcon.put("COG" ,"Congo");
        codeToIcon.put("COL" ,"Colombia");
        codeToIcon.put("CPV" ,"Cape Verde");
        codeToIcon.put("CRI" ,"Costa Rica");
        codeToIcon.put("CUB" ,"Cuba");
        codeToIcon.put("CYP" ,"Cyprus");
        codeToIcon.put("CZE" ,"Czech Republic");
        codeToIcon.put("DEU" ,"Germany");
        codeToIcon.put("DNK" ,"Denmark");
        codeToIcon.put("DOM" ,"Dominican Republic");
        codeToIcon.put("DZA" ,"Algeria");
        codeToIcon.put("ECU" ,"Ecuador");
        codeToIcon.put("EGY" ,"Egypt");
        codeToIcon.put("ERI" ,"Eritrea");
        codeToIcon.put("ESH" ,"Western Sahara");
        codeToIcon.put("ESP" ,"Spain");
        codeToIcon.put("EST" ,"Estonia");
        codeToIcon.put("ETH" ,"Ethiopia");
        codeToIcon.put("FIN" ,"Finland");
        codeToIcon.put("FJI" ,"Fiji");
        codeToIcon.put("FRA" ,"France");
        codeToIcon.put("GAB" ,"Gabon");
        codeToIcon.put("GBR" ,"United Kingdom");
        codeToIcon.put("GEO" ,"Georgia");
        codeToIcon.put("GHA" ,"Ghana");
        codeToIcon.put("GIB" ,"Gibraltar");
        codeToIcon.put("GIN" ,"Guinea");
        codeToIcon.put("GLP" ,"Guadeloupe");
        codeToIcon.put("GMB" ,"Gambia");
        codeToIcon.put("GNB" ,"Guinea-Bissau");
        codeToIcon.put("GNQ" ,"Equatorial Guinea");
        codeToIcon.put("GRC" ,"Greece");
        codeToIcon.put("GRD" ,"Grenada");
        codeToIcon.put("GRL" ,"Greenland");
        codeToIcon.put("GTM" ,"Guatemala");
        codeToIcon.put("GUF" ,"French Guiana");
        codeToIcon.put("GUM" ,"Guam");
        codeToIcon.put("GUY" ,"Guyana");
        codeToIcon.put("HKG" ,"Hong Kong");
        codeToIcon.put("HND" ,"Honduras");
        codeToIcon.put("HRV" ,"Croatia");
        codeToIcon.put("HTI" ,"Haiti");
        codeToIcon.put("HUN" ,"Hungary");
        codeToIcon.put("IDN" ,"Indonesia");
        codeToIcon.put("IND" ,"India");
        codeToIcon.put("IRL" ,"Ireland");
        codeToIcon.put("IRN" ,"Iran");
        codeToIcon.put("IRQ" ,"Iraq");
        codeToIcon.put("ISL" ,"Iceland");
        codeToIcon.put("ISR" ,"Israel");
        codeToIcon.put("ITA" ,"Italy");
        codeToIcon.put("JAM" ,"Jamaica");
        codeToIcon.put("JPN" ,"Japan");
        codeToIcon.put("KAZ" ,"Kazakhstan");
        codeToIcon.put("KEN" ,"Kenya");
        codeToIcon.put("KGZ" ,"Kyrgyzstan");
        codeToIcon.put("KHM" ,"Cambodia");
        codeToIcon.put("KOR" ,"South Korea");
        codeToIcon.put("KWT" ,"Kuwait");
        codeToIcon.put("LBN" ,"Lebanon");
        codeToIcon.put("LBR" ,"Liberia");
        codeToIcon.put("LIE" ,"Liechtenstein");
        codeToIcon.put("LKA" ,"Sri Lanka");
        codeToIcon.put("LSO" ,"Lesotho");
        codeToIcon.put("LTU" ,"Lithuania");
        codeToIcon.put("LUX" ,"Luxembourg");
        codeToIcon.put("LVA" ,"Latvia");
        codeToIcon.put("MAC" ,"Macao");
        codeToIcon.put("MAR" ,"Morocco");
        codeToIcon.put("MCO" ,"Monaco");
        codeToIcon.put("MDA" ,"Moldova");
        codeToIcon.put("MDG" ,"Madagascar");
        codeToIcon.put("MDV" ,"Maldives");
        codeToIcon.put("MEX" ,"Mexico");
        codeToIcon.put("MKD" ,"Macedonia");
        codeToIcon.put("MLI" ,"Mali");
        codeToIcon.put("MLT" ,"Malta");
        codeToIcon.put("MMR" ,"Myanmar");
        codeToIcon.put("MNE" ,"Montenegro");
        codeToIcon.put("MNG" ,"Mongolia");
        codeToIcon.put("MOZ" ,"Mozambique");
        codeToIcon.put("MRT" ,"Mauritania");
        codeToIcon.put("MTQ" ,"Martinique");
        codeToIcon.put("MUS" ,"Mauritius");
        codeToIcon.put("MWI" ,"Malawi");
        codeToIcon.put("MYS" ,"Malaysia");
        codeToIcon.put("NAM" ,"Namibia");
        codeToIcon.put("NER" ,"Niger");
        codeToIcon.put("NGA" ,"Nigeria");
        codeToIcon.put("NIC" ,"Nicaragua");
        codeToIcon.put("NLD" ,"Netherlands");
        codeToIcon.put("NOR" ,"Norway");
        codeToIcon.put("NPL" ,"Nepal");
        codeToIcon.put("NZL" ,"New Zealand");
        codeToIcon.put("OMN" ,"Oman");
        codeToIcon.put("PAK" ,"Pakistan");
        codeToIcon.put("PAN" ,"Panama");
        codeToIcon.put("PER" ,"Peru");
        codeToIcon.put("PHL" ,"Philippines");
        codeToIcon.put("PNG" ,"Papua New Guinea");
        codeToIcon.put("POL" ,"Poland");
        codeToIcon.put("PRI" ,"Puerto Rico");
        codeToIcon.put("PRK" ,"North Korea");
        codeToIcon.put("PRT" ,"Portugal");
        codeToIcon.put("PRY" ,"Paraguay");
        codeToIcon.put("QAT" ,"Qatar");
        codeToIcon.put("ROU" ,"Romania");
        codeToIcon.put("RUS" ,"Russian Federation");
        codeToIcon.put("RWA" ,"Rwanda");
        codeToIcon.put("SAU" ,"Saudi Arabia");
        codeToIcon.put("SDN" ,"Sudan");
        codeToIcon.put("SEN" ,"Senegal");
        codeToIcon.put("SGP" ,"Singapore");
        codeToIcon.put("SLE" ,"Sierra Leone");
        codeToIcon.put("SLV" ,"El Salvador");
        codeToIcon.put("SMR" ,"San Marino");
        codeToIcon.put("SOM" ,"Somalia");
        codeToIcon.put("SRB" ,"Serbia");
        codeToIcon.put("SUR" ,"Suriname");
        codeToIcon.put("SVK" ,"Slovakia");
        codeToIcon.put("SVN" ,"Slovenia");
        codeToIcon.put("SWE" ,"Sweden");
        codeToIcon.put("SWZ" ,"Swaziland");
        codeToIcon.put("SYC" ,"Seychelles");
        codeToIcon.put("SYR" ,"Syrian Arab Republic");
        codeToIcon.put("TCD" ,"Chad");
        codeToIcon.put("TGO" ,"Togo");
        codeToIcon.put("THA" ,"Thailand");
        codeToIcon.put("TJK" ,"Tajikistan");
        codeToIcon.put("TKM" ,"Turkmenistan");
        codeToIcon.put("TON" ,"Tonga");
        codeToIcon.put("TTO" ,"Trinidad and Tobago");
        codeToIcon.put("TUN" ,"Tunisia");
        codeToIcon.put("TUR" ,"Turkey");
        codeToIcon.put("TWN" ,"Taiwan");
        codeToIcon.put("TZA" ,"Tanzania");
        codeToIcon.put("UGA" ,"Uganda");
        codeToIcon.put("UKR" ,"Ukraine");
        codeToIcon.put("URY" ,"Uruguay");
        codeToIcon.put("USA" ,"United States");
        codeToIcon.put("UZB" ,"Uzbekistan");
        codeToIcon.put("VEN" ,"Venezuela");
        codeToIcon.put("VNM" ,"Vietnam");
        codeToIcon.put("WSM" ,"Samoa");
        codeToIcon.put("YEM" ,"Yemen");
        codeToIcon.put("ZAF" ,"South Africa");
        codeToIcon.put("ZMB" ,"Zambia");
        codeToIcon.put("ZWE" ,"Zimbabwe");

        return null;
    }


}
